theme: minima
title: Races
description: My Race Results
url: "https://nizamogluyekta.github.io"
baseurl: "/races"

# Enable plugins that GitHub Pages supports
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Custom styling
sass:
  style: compressed
